# Generated by Django 5.2 on 2025-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('nuts_tg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='selected_items',
            field=models.ManyToManyField(blank=True, related_name='users', to='nuts_tg_app.categoryitem', verbose_name='Selected Items'),
        ),
    ]
