# Generated by Django 5.2 on 2025-04-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fruits', 'Фрукты'), ('vegetables', 'Овощи'), ('nuts', 'Орехи')], max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Item Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuts_tg_app.category')),
            ],
            options={
                'verbose_name_plural': 'Category Items',
            },
        ),
    ]
